test2: main.o hello.o goodbye.o
	gcc -o test2 main.o hello.o goodbye.o
main.o: main.c
	gcc -o main.o -c main.c
hello.o: hello.c
	gcc -o hello.o -c hello.c
goodbye.o: goodbye.c
	gcc -o goodbye.o -c goodbye.c
